name: "Discord Notification"
on: [push, pull_request, issues]
env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: Triggering Push Discord Notification
        if: github.event_name == 'push' && github.repository_owner == 'hugsy'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: ${{ github.actor }} pushed to `${{ github.ref }}`
          description: |
            **Commit delta**: `${{ github.event.before }}` → `${{ github.event.after }}`
            ---
            **Changes**: ${{ github.event.compare }}
            ---
            **Commits**:
              ● ${{ join(github.event.commits.*.message, '
              ● ') }}

          color: 0x0000ff
          username: ${{ github.actor }} on CFB
          avatar_url: https://i.imgur.com/O4RKNqj.png

      - name: Triggering Pull Request Discord Notification
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.repository_owner == 'hugsy'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: ${{ github.actor }} created a new Pull Request (`#${{ github.event.pull_request.number }}`)
          description: |
            **${{ github.event.pull_request.title }}**

            ${{ github.event.pull_request.body }}

            ---
            Link: ${{ github.event.pull_request.html_url }}
          color: 0xff0000
          username: ${{ github.actor }} on CFB
          avatar_url: https://i.imgur.com/O4RKNqj.png
          
      - name: Triggering Issue Discord Notification
        if: github.event_name == 'issues' && github.event.action == 'opened' && github.repository_owner == 'hugsy'
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: ${{ github.actor }} created a new Issue (`#${{ github.event.issue.number }}`)
          description: |
            **${{ github.event.issue.title }}**

            ${{ github.event.issue.body }}

            ---
            Link: ${{ github.event.issue.html_url }}
          color: 0x00ff00
          username: ${{ github.actor }} on CFB
          avatar_url: https://i.imgur.com/O4RKNqj.png
